name = "Opti Craft"
author = "Ricky12Awesome"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "413ce503563179859de3bec2755034b04e4bff80d942fbc9580c8c74cfc34644"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0-beta.2"
